### DISCUSSION TITLE
generate_schema_name handling.

### DISCUSSION THREAD

**Discussion by jaredvivints** [brooklyn-data/dbt_artifacts#268] [Q&A]
Hi,

I've got a situation where I can't add the results of this package to a custom schema in Snowflake. We're using generate_schema_name to push custom folders into specific schemas. I for the life of me can't figure out how to make this work wanting the dbt_artifacts objects to go into our src_dbt_artifact schema. 

Here is our generate_schema_name
{% macro generate_schema_name(custom_schema_name, node) -%}

    {%- set default_schema = target.schema -%}
    {%- if custom_schema_name is none -%}

        {{ default_schema }}

    {%- else -%}

        {{ custom_schema_name | trim }}

    {%- endif -%}

{%- endmacro %}

Here is our dbt_project.yml config with the models block. 

models:
  dp_dbt:
    dbt_artifacts:
      +database: "{{ target.name + '_DB' }}" # optional, default is your target database
      +schema: src_dbt_artifact # optional, default is your target schema
      staging:
        +database: "{{ target.name + '_DB' }}" # optional, default is your target database
        +schema: src_dbt_artifact # optional, default is your target schema
      sources:
        +database: "{{ target.name + '_DB' }}" # optional, default is your target database
        +schema: src_dbt_artifact # optional, default is your target schema

Would love any thoughts. I know the docs say "Be aware of any impact that [generate_database_name](https://docs.getdbt.com/docs/building-a-dbt-project/building-models/using-custom-databases#generate_database_name) and [generate_schema_name](https://docs.getdbt.com/docs/building-a-dbt-project/building-models/using-custom-schemas#how-does-dbt-generate-a-models-schema-name) macros may have on the final database/schema."

I'm just wondering how to handle this scenario. 

Thanks.

**Comment by T-Dunlap** [comment]
Hey @jaredvivints! I don't think you'll need to edit the `generate_database_name` or `generate_schema_name` macros... you should be able to handle this in the configs of the dbt_project.yml file.  Did you define the variables section? 

I think it should look something like this...
```
vars:
  dbt_artifacts:
    dbt_artifacts_database: "{{ target.name + '_DB' }}"  # optional, default is your target database
    dbt_artifacts_schema: src_dbt_artifact # optional, default is 'dbt_artifacts'
    dbt_artifacts_create_schema: true # optional, true|false set to false if you don't have privileges to create schema, default is true

models:

  dbt_artifacts:
    +schema: src_dbt_artifact 
    +database: "{{ target.name + '_DB' }}"
    staging:
      +schema: src_dbt_artifact
```
