### ISSUE TITLE
`dbt_project.yml` sets a custom schema

### ISSUE THREAD

**Issue by clrcrl** [brooklyn-data/dbt_artifacts#12]
This repo sets a custom schema here:
https://github.com/tailsdotcom/dbt_artifacts/blob/main/dbt_project.yml#L8

```yml
models:
  dbt_artifacts:
    +schema: default_dbt_artifacts_schema
```

I think in most cases I'd recommend that the custom schema not be set (and therefore the default schema gets used).

Is there a particular reason for setting this value?
