### ISSUE TITLE
INFORMATION_SCHEMA_SCHEMA is created in Snowflake when using custom schemas

### ISSUE THREAD

**Issue by ghost** [brooklyn-data/dbt_artifacts#150]
After adding the dbt_artifacts package to my dbt/Snowflake project, I've noticed that a schema named `INFORMATION_SCHEMA_SCHEMA` appears. 

The following views are the only objects in this schema:

```
DIM_DBT__EXPOSURES
DIM_DBT__MODELS
DIM_DBT__SEEDS
DIM_DBT__SNAPSHOTS
DIM_DBT__SOURCES
DIM_DBT__TESTS
FCT_DBT__INVOCATIONS
FCT_DBT__MODEL_EXECUTIONS
FCT_DBT__SEED_EXECUTIONS
FCT_DBT__SNAPSHOT_EXECUTIONS
FCT_DBT__TEST_EXECUTIONS
STG_DBT__EXPOSURES
STG_DBT__INVOCATIONS
STG_DBT__MODELS
STG_DBT__MODEL_EXECUTIONS
STG_DBT__SEEDS
STG_DBT__SEED_EXECUTIONS
STG_DBT__SNAPSHOTS
STG_DBT__SNAPSHOT_EXECUTIONS
STG_DBT__SOURCES
STG_DBT__TESTS
STG_DBT__TEST_EXECUTIONS
```

This appears to be the result of the package writing to the INFORMATION_SCHEMA[1] and dbt configured to use custom schemas[2].

Here is the relevant configuration I've added to my project before running `dbt build`.

**dbt_project.yml**
```
...
vars:
  dbt_artifacts:
    dbt_artifacts_schema: 'DBT_ARTIFACT_SCHEMA'
...
# Ensure the dbt Artifacts Tables Exist
on-run-start: "{{ dbt_artifacts.create_dbt_artifacts_tables() }}"
# Upload dbt Artifacts to Snowflake
on-run-end: "{{ dbt_artifacts.upload_results(results) }}"
```

**packages.yml**
```
packages:
  - git: https://github.com/brooklyn-data/dbt_artifacts.git
    revision: 1.0.0b1
```

[1] https://docs.snowflake.com/en/sql-reference/info-schema.html
[2] https://docs.getdbt.com/docs/building-a-dbt-project/building-models/using-custom-schemas
