### ISSUE TITLE
Fix Ci/CD

### ISSUE THREAD

**Issue by kgpayne** [brooklyn-data/dbt_artifacts#22]
CI/CD is failing on `dbt seed` for no obvious reason. Runs locally fine with the same credentials 🤦‍♂️

![Screenshot 2021-04-16 at 15 03 10](https://user-images.githubusercontent.com/5585874/115038618-9c20ae00-9ec7-11eb-878a-7f417b28dad9.png)

**Comment by kgpayne** [comment]
@clrcrl am I missing anything obvious? This `integration_testing` pattern is new to me.

**Comment by kgpayne** [comment]
Removing `--warn-error` in our CI script as a last resort. Seems to be a bug in `dbt` as not combinations of seed configs worked:

```yaml
seeds:
  +quote_columns: false

seeds:
  artifacts_integration_tests:
    +quote_columns: false

seeds:
  artifacts_integration_tests:
  +quote_columns: false
```
