### ISSUE TITLE
[Bug]: Windows file escape for `checksum`

### ISSUE THREAD

**Issue by frannydelaney** [brooklyn-data/dbt_artifacts#303]
## Overview

Our Windows users are receiving errors when running `dbt_artifacts` due to how `dbt_core` handles large seed files (information [found here](https://github.com/dbt-labs/dbt-core/issues/6875) on currently handling). When `checksum` is just stored as a file path, they encounter the same error as was reported [here](https://github.com/brooklyn-data/dbt_artifacts/issues/156) and resolved [here](https://github.com/brooklyn-data/dbt_artifacts/pull/160)

Error message:
```
14:56:11
14:56:11  Running 3 on-run-end hooks
14:56:11  Uploading model executions
14:56:11  Uploading seed executions
14:56:13  Uploading snapshot executions
14:56:13  Uploading test executions
14:56:13  Uploading exposures
14:56:13  Uploading tests
14:56:22  Uploading seeds
14:56:22  Database error while running on-run-end
14:56:23  Encountered an error:
Database Error
  001831 (42601): SQL compilation error: error line 2,019 at position 16
  Invalid unicode escape sequence '\u'; should be exactly 4 digits.
```

I haven't contributed to the project but would be happy to give it a shot if it's as simple as the previously noted change.

## How to reproduce

Run `dbt_artifacts` on Windows machine where at least one seeds exceeds 1 MG.

## Expected behaviour

Escape the `checksum` column for this situation as with the `original_file_path` escape added [here](https://github.com/brooklyn-data/dbt_artifacts/pull/160)

## Environment

Results of running `dbt --version`:

```sh
Core:
  - installed: 1.3.1
  - latest:    1.5.0 - Update available!

  Your version of dbt-core is out of date!
  You can find instructions for upgrading here:
  https://docs.getdbt.com/docs/installation
```

Please paste the contents of your `packages.yml` file here:

```yml
packages:
  - package: brooklyn-data/dbt_artifacts
    version: 2.2.2
  - package: calogica/dbt_date
    version: 0.5.7
  - package: calogica/dbt_expectations
    version: 0.5.6
  - package: dbt-labs/dbt_utils
    version: 0.8.6
  - package: elementary-data/elementary
    version: 0.7.3
    ## Docs: https://docs.elementary-data.com
  - package: re-data/re_data
    version: 0.10.6
```
