### ISSUE TITLE
[Bug]: Escape quotations when loading `models.meta`

### ISSUE THREAD

**Issue by waligob** [brooklyn-data/dbt_artifacts#323]
## Overview

When loading the `models` source, the column `meta` [is loaded with the value](https://github.com/brooklyn-data/dbt_artifacts/blob/95e958a06e507085a9da6412c6efbf2a94cfb7f6/macros/upload_models.sql#L74) `parse_json('{{ tojson(model.config.meta) }}')`. This can cause syntax errors in the compiled SQL when there are quotations in the `meta` value, such as in the following instance:

<img width="1079" alt="image" src="https://github.com/brooklyn-data/dbt_artifacts/assets/93673562/ddb3bd29-6cf4-42c9-b0eb-257d10787213">

_sample of `insert`SQL script for `models`_

Here is how that `meta` value is represented in the model's `.yml` config:

```
version: 2
models:
  - name: table
    meta:
        grain: Each row is one week's performance data for one team, up against its goals
        description: Table used to track individual team progress toward goals
```

## How to reproduce
Configure a dbt model where the `meta` property contains a single quotation, and run the model with `dbt run --select <MODEL>`

## Expected behaviour

dbt_artifact's `on-run-end` hook should successfully load records into `models`

## Environment

Results of running `dbt --version`: 

```sh
`1.4.5`
```

Please paste the contents of your `packages.yml` file here:

```yml
packages:
  - package: dbt-labs/dbt_utils
    version: [">=1.0.0", "<1.1.0"]
  - package: calogica/dbt_expectations
    version: [">=0.8.0", "<0.9.0"]
  - package: dbt-labs/codegen
    version: [">=0.9.0", "<0.10.0"]
  - package: data-mie/dbt_profiler
    version: [">=0.6.0", "<0.7.0"]
  - package: dbt-labs/dbt_project_evaluator
    version: [">=0.5.0", "<0.6.0"]
  - package: dbt-labs/metrics
    version: [">=1.4.0", "<1.5.0"]
  - package: brooklyn-data/dbt_artifacts
    version: [">=2.3.0", "<2.4.0"]
  - package: elementary-data/elementary
    version: [">=0.7.0", "<0.8.0"]
  - package: dbt-labs/audit_helper
    version: [">=0.9.0","<1.0.0"]

```
