### ISSUE TITLE
[Bug]: dbt_artifacts own code giving syntax error

### ISSUE THREAD

**Issue by calkan-cue** [brooklyn-data/dbt_artifacts#331]
## Overview

The package's own code throwing error. 
## How to reproduce

dbt build --select dbt_artifacts

## Expected behaviour
I was expecting it to run fine and create necessary tables but instead it throws syntax errors. 

## Screenshots

> 07:00:48  Completed with 11 errors and 0 warnings:
> 07:00:48  
> 07:00:48  Database Error in model stg_dbt__model_executions (models/staging/stg_dbt__model_executions.sql)
> 07:00:48    Syntax error: Expected ")" but got "(" at [19:148]
> 07:00:48    compiled Code at target/run/dbt_artifacts/models/staging/stg_dbt__model_executions.sql
> 07:00:48  
> 07:00:48  Database Error in model stg_dbt__exposures (models/staging/stg_dbt__exposures.sql)
> 07:00:48    Syntax error: Expected ")" but got "(" at [19:148]
> 07:00:48    compiled Code at target/run/dbt_artifacts/models/staging/stg_dbt__exposures.sql
> 07:00:48  
> 07:00:48  Database Error in model stg_dbt__seed_executions (models/staging/stg_dbt__seed_executions.sql)
> 07:00:48    Syntax error: Expected ")" but got "(" at [19:148]
> 07:00:48    compiled Code at target/run/dbt_artifacts/models/staging/stg_dbt__seed_executions.sql
> 07:00:48  
> 07:00:48  Database Error in model stg_dbt__snapshots (models/staging/stg_dbt__snapshots.sql)
> 07:00:48    Syntax error: Expected ")" but got "(" at [19:148]
> 07:00:48    compiled Code at target/run/dbt_artifacts/models/staging/stg_dbt__snapshots.sql
> 07:00:48  
> 07:00:48  Database Error in model stg_dbt__models (models/staging/stg_dbt__models.sql)
> 07:00:48    Syntax error: Expected ")" but got "(" at [19:148]
> 07:00:48    compiled Code at target/run/dbt_artifacts/models/staging/stg_dbt__models.sql
> 07:00:48  
> 07:00:48  Database Error in model stg_dbt__snapshot_executions (models/staging/stg_dbt__snapshot_executions.sql)
> 07:00:48    Syntax error: Expected ")" but got "(" at [19:148]
> 07:00:48    compiled Code at target/run/dbt_artifacts/models/staging/stg_dbt__snapshot_executions.sql
> 07:00:48  
> 07:00:48  Database Error in model stg_dbt__seeds (models/staging/stg_dbt__seeds.sql)
> 07:00:48    Syntax error: Expected ")" but got "(" at [19:148]
> 07:00:48    compiled Code at target/run/dbt_artifacts/models/staging/stg_dbt__seeds.sql
> 07:00:48  
> 07:00:48  Database Error in model stg_dbt__test_executions (models/staging/stg_dbt__test_executions.sql)
> 07:00:48    Syntax error: Expected ")" but got "(" at [19:148]
> 07:00:48    compiled Code at target/run/dbt_artifacts/models/staging/stg_dbt__test_executions.sql
> 07:00:48  
> 07:00:48  Database Error in model stg_dbt__sources (models/staging/stg_dbt__sources.sql)
> 07:00:48    Syntax error: Expected ")" but got "(" at [19:148]
> 07:00:48    compiled Code at target/run/dbt_artifacts/models/staging/stg_dbt__sources.sql
> 07:00:48  
> 07:00:48  Database Error in model stg_dbt__tests (models/staging/stg_dbt__tests.sql)
> 07:00:48    Syntax error: Expected ")" but got "(" at [19:148]
> 07:00:48    compiled Code at target/run/dbt_artifacts/models/staging/stg_dbt__tests.sql
> 07:00:48    

## Environment

Results of running `dbt --version`:

```sh
Core:
  - installed: 1.4.5
  - latest:    1.5.0 - Update available!

  Your version of dbt-core is out of date!
  You can find instructions for upgrading here:
  https://docs.getdbt.com/docs/installation

Plugins:
  - bigquery: 1.4.1 - Update available!

  At least one plugin is out of date or incompatible with dbt-core.
  You can find instructions for upgrading here:
```

Please paste the contents of your `packages.yml` file here:  

```yml
 packages:
  - package: dbt-labs/codegen
    version: 0.9.0
  - package: dbt-labs/dbt_project_evaluator
    version: 0.4.1
  - package: dbt-labs/dbt_external_tables
    version: 0.8.2
  - package: brooklyn-data/dbt_artifacts
    version: 2.3.0
  - package: fivetran/shopify
    version: [">=0.8.0", "<0.9.0"]
  - package: fivetran/ad_reporting
    version: [">=1.3.0", "<1.4.0"]
  - package: fivetran/netsuite
    version: [">=0.7.0", "<0.8.0"]
  - package: fivetran/salesforce
    version: [">=0.8.0", "<0.9.0"]
  - package: dbt-labs/metrics
    version: [">=1.4.0", "<1.5.0"]

```
