### ISSUE TITLE
[Bug]: Invocations fails with dbt-bigquery 1.5.0

### ISSUE THREAD

**Issue by d-cole** [brooklyn-data/dbt_artifacts#337]
## Overview

Same issue as https://github.com/brooklyn-data/dbt_artifacts/issues/296 https://github.com/brooklyn-data/dbt_artifacts/issues/307 but for dbt-bigquery==1.5.0. I am encountering this error when adding dbt_artifacts to a project using dbt-bigquery 1.5.0. 

## How to reproduce
 - Upgrade dbt-bigquery to 1.5.0 and `dbt run -s dbt_artifacts`
 
## Screenshots

```
14:35:41  Uploading invocations
14:35:41  Database error while running on-run-end
14:35:41  
14:35:41  Finished running 11 incremental models, 23 view models in 0 hours 0 minutes and 57.65 seconds (57.65s).
14:35:41  
14:35:41  Completed with 1 error and 0 warnings:
14:35:41  
14:35:41  on-run-end failed, error:
14:35:41   Object of type WarnErrorOptions is not JSON serializable
```

## Environment

Results of running `dbt --version`:

```sh
Core:
  - installed: 1.5.0
  - latest:    1.5.0 - Up to date!

Plugins:
  - bigquery: 1.5.0 - Update available!
```

Please paste the contents of your `packages.yml` file here:
 dbt_artifacts was pinned to f38da16068416d1e2b1405686be953231ae0cef8 to test if snowflake fix worked for BQ as well.
```yml
packages:
   - package: dbt-labs/dbt_utils
    version: 0.9.2
  - git: https://github.com/dbt-labs/dbt-codegen.git
    revision: c77d28e20017c714dfe5045f8f2e993632870d25
  - package: EqualExperts/dbt_unit_testing
    version: 0.2.7
  - git: https://github.com/brooklyn-data/dbt_artifacts
    revision: f38da16068416d1e2b1405686be953231ae0cef8 
```
