### ISSUE TITLE
[Bug]: Error when upgrading to 2.4.0 on BigQuery

### ISSUE THREAD

**Issue by jdewet03** [brooklyn-data/dbt_artifacts#343]
## Overview

We're unable to successfully run` dbt run --select dbt_artifacts `when upgrading to 2.4.0

on-run-end failed, error:
The query is too large. The maximum standard SQL query length is 1024.00K characters, including comments and white space characters.

## How to reproduce

On dbt solution using BigQuery:
- Implement and run dbt_artifacts version 2.3.0
- Upgrade dbt_artifacts version to 2.4.0
- Run:  `dbt run --select dbt_artifacts `

We also tried deleting our dbt_artifacts schemas but same error

## Expected behaviour

We expect to see the dbt command above complete succesfully

## Screenshots

<img width="1144" alt="image" src="https://github.com/brooklyn-data/dbt_artifacts/assets/131745528/f6a98c26-c99c-48cb-8b2f-2a98917f8939">

## Environment

Results of running `dbt --version`: 

```sh
1.4.6
```

Please paste the contents of your `packages.yml` file here:

```yml
packages:
  - package: dbt-labs/audit_helper
    version: [">=0.5.0", "<1.0.0"]

  - package: dbt-labs/dbt_utils
    version: [">=1.0.0", "<2.0.0"]
    
  - package: dbt-labs/codegen
    version: [">=0.5.0", "<1.0.0"]

  - package: data-mie/dbt_profiler
    version: [">=0.5.0", "<1.0.0"]

  - package: dbt-labs/dbt_project_evaluator
    version: [">=0.2.0", "<1.0.0"]

  - package: calogica/dbt_date
    version: [">=0.7.0", "<1.0.0"]

  - package: brooklyn-data/dbt_artifacts
    version: [">=2.3.0", "<3.0.0"]
```
