### ISSUE TITLE
[Bug]: Does not work with Snowflake and quoting true 

### ISSUE THREAD

**Issue by ghost** [brooklyn-data/dbt_artifacts#360]
## Overview

When used in a project with snowflake as target and quoting:identifier:true it fails to load the models. Setting quoting:identifier:false on the model dbt_artifacts in dbt_project.yml does not work.

## How to reproduce

Create a project with target on Snowflake and set the quoting to true on identifiers. Add the dbt_artifacts package and run it.

## Expected behaviour

That it would work with quoting:true but it seems that there is inconsistent usa of case in the package code.

## Environment

Core:
  - installed: 1.5.0
Plugins:
  - snowflake: 1.5.0 

```sh
# Add the results here
```

Please paste the contents of your `packages.yml` file here:

```
packages:
  - git: "https://github.com/dbt-labs/dbt-utils.git" # git URL
    revision: 1.1.0 # tag or branch name
  - package: brooklyn-data/dbt_artifacts
    version: 2.4.2
```
