### ISSUE TITLE
[Bug]: Fails Running on BigQuery with PARSE_JSON Error Message

### ISSUE THREAD

**Issue by codigo-ergo-sum** [brooklyn-data/dbt_artifacts#363]
## Overview

I'm trying to use dbt-artifacts on bigquery. Installed from scratch, running dbt run --select dbt_artifacts , I'm getting this error message:
```
22:56:28  on-run-end failed, error:
22:56:28   Invalid input: Input number: 1687473876.057356 cannot round-trip through string representation; error in PARSE_JSON expression
```

## How to reproduce

1. Add dbt-artifacts to the packages.yml file
2. Run `dbt deps`
3. Run `dbt run --select dbt_artifacts`

## Expected behaviour

dbt-artifacts would run successfully and upload results :)

## Screenshots

![image](https://github.com/brooklyn-data/dbt_artifacts/assets/65506623/863e86fc-20de-44c6-aabb-14b316bee1db)

(I deleted the URL after "Bigquery Adapter" from the screenshot)

## Environment

Results of running `dbt --version`:

```sh
Core:
  - installed: 1.5.1
  - latest:    1.5.2 - Update available!

  Your version of dbt-core is out of date!
  You can find instructions for upgrading here:
  https://docs.getdbt.com/docs/installation

Plugins:
  - bigquery: 1.5.1 - Update available!

  At least one plugin is out of date or incompatible with dbt-core.
  You can find instructions for upgrading here:
  https://docs.getdbt.com/docs/installation

```

Please paste the contents of your `packages.yml` file here:

```yml
packages:
  - package: dbt-labs/dbt_utils
    version: 1.0.0

  - package: tnightengale/dbt_meta_testing
    version: 0.3.6

  - package: fivetran/salesforce_formula_utils
    version: [">=0.8.0", "<0.9.0"]

  - package: brooklyn-data/dbt_artifacts
    version: 2.4.2
```
