### ISSUE TITLE
[Bug]: Error from snowflake__get_model_executions_dml_sql missing value

### ISSUE THREAD

**Issue by kenpokiwi** [brooklyn-data/dbt_artifacts#385]
## Overview

When called following a failed call to a macro, the insert into model_executions generated is missing a value. "Inconsistent number of values in the VALUES clause expecting 16 but got 15".

## How to reproduce

Build a model that calls a macro which raises a user defined compiler error "do exceptions.raise_compiler_error(err)"
Call dbt_artifacts.upload_results(results) to upload results.

## Expected behaviour

Generation of a valid insert statement with the required 16 values from the snowflake__get_model_executions_dml_sql macro. 

Within the {% if model.timing != [] %} block need additional "{% else %} null" block for each  {% for stage in model.timing if stage.name == "<stage name>" %} to catch missing stage times within timing.

## Screenshots

![image](https://github.com/brooklyn-data/dbt_artifacts/assets/89880566/c5be25c4-d334-47e8-b330-d335471a4ef6)

## Environment

Results of running `dbt --version`: 1.6.2

```sh
1.6.2
```

Please paste the contents of your `packages.yml` file here:

```yml
packages:
    - package: dbt-labs/dbt_utils
    version: 1.1.0
  - package: dbt-labs/dbt_external_tables
    version: 0.8.0
  - package: dbt-labs/audit_helper
    version: 0.6.0
  - package: calogica/dbt_expectations
    version: 0.8.5
    # <see https://github.com/calogica/dbt-expectations/releases/latest> for the latest version tag
  - package: brooklyn-data/dbt_artifacts
    version: 2.5.0
```
