### ISSUE TITLE
[Bug]: Upload model is having incorrect column order 

### ISSUE THREAD

**Issue by il-dat** [brooklyn-data/dbt_artifacts#392]
## Overview

The [`model.sql` model](https://github.com/brooklyn-data/dbt_artifacts/blob/main/models/sources/models.sql) has the columns in following order:
- `cast(null as {{ type_string() }}) as command_invocation_id`
- `cast(null as {{ type_string() }}) as node_id`
- ...

But the [macro](https://github.com/brooklyn-data/dbt_artifacts/blob/069d71ce1d6a041e201ce11b349ed38f34fe1cdd/macros/upload_results/get_column_name_lists.sql#L76) (upload result) is following the reversed order:
- `node_id`
- `command_invocation_id`

## How to reproduce

Encountered in `snowflake` and `dbt-artifacts` v2.6.0 

## Expected behaviour

Make sure the column order is matching to the upload macros

## Screenshots

![image](https://github.com/brooklyn-data/dbt_artifacts/assets/103571964/3c66037b-32bd-4437-b08f-6987f513fcad)

## Environment

Results of running `dbt --version`: 1.6 latest

Please paste the contents of your `packages.yml` file here:

```yml
packages:
  - package: dbt-labs/dbt_utils
    version: 1.1.1
  - package: dbt-labs/codegen
    version: 0.10.0
  - package: dbt-labs/dbt_project_evaluator
    version: 0.7.3
  - package: infinitelambda/dq_tools
    version: [">=1.4.0", "<1.5.0"]
  - package: get-select/dbt_snowflake_monitoring
    version: 4.5.1
  - package: brooklyn-data/dbt_artifacts
    version: [">=2.6.0", "<2.7.0"]
```
