### ISSUE TITLE
[Bug]: dbt_artifacts cannot upload artifacts when the dbt_project has microbatch models

### ISSUE THREAD

**Issue by steveh-101** [brooklyn-data/dbt_artifacts#476]
## Overview

if the dbt_project contains "microbatch" models - json is not serializable when uploading artifacts. 

Related to [this](https://github.com/dbt-labs/dbt-core/pull/11187)

## How to reproduce

Try to use dbt_artifacts within a project that has micobatch style incremental models

## Expected behaviour

That dbt_artifacts works as normal regardless of the strategy used for incremental model

## Screenshots

![Image](https://github.com/user-attachments/assets/a2a842cf-1f9b-42d3-9159-5bda315b2b50)

## Environment

```sh
Core:
  - installed: 1.9.1
  - latest:    1.9.1 - Up to date!

Plugins:
  - snowflake: 1.9.0 - Up to date!

```

Please paste the contents of your `packages.yml` file here:

```yml
packages:
  - package: dbt-labs/dbt_external_tables
    version: 0.11.1
  - package: dbt-labs/codegen
    version: 0.13.1
  - package: brooklyn-data/dbt_artifacts
    version: 2.8.0
  - package: calogica/dbt_expectations
    version: 0.10.4
  - package: dbt-labs/audit_helper
    version: 0.12.1
  - package: get-select/dbt_snowflake_monitoring
    version: 5.3.1
```
