### ISSUE TITLE
vars not loaded in invocations source for BigQuery target

### ISSUE THREAD

**Issue by davidmunoz4185** [brooklyn-data/dbt_artifacts#481]
Trying to identify specific executions by description:

dbt run -s staging --vars '{description: test_description}'

Notice that in postgres invocations info is loaded in invocations_args, otherwise in Bigquery is not.

This is the config in dbt_project.yml:

```

vars:
  dbt_artifacts_exclude_all_results: true

models:
  dbt_artifacts:
    +enabled: false
    sources:
      +enabled: true
      +schema: dbt_artifacts_src
  integration_tests:
      materialized: table
      staging:
        +schema: dbt_artifacts_tst

on-run-end:
  - "{{ dbt_artifacts.upload_results(results) }}"
```
