### ISSUE TITLE
[Bug]: Found unexpected 'endmacro' block tag. in file macros/upload_results/insert_into_metadata_table.sql

### ISSUE THREAD

**Issue by inactivekathework** [brooklyn-data/dbt_artifacts#501]
## Overview

Found unexpected 'endmacro' block tag. in file
macros/upload_results/insert_into_metadata_table.sql
There is 7 macros, but 8 endmacro statements 
## How to reproduce

1) dbt build --full-refresh --select state:modified+
2) When you use the macro from insert_into_metadata_table
3) warning comes

## Expected behaviour

I expect there to be no warning

## Screenshots

![Image](https://github.com/user-attachments/assets/fdbf20cf-cbf7-4651-85b9-6983e1858190)

![Image](https://github.com/user-attachments/assets/da319257-8c40-4354-8fe0-d43fdbe83d30)

## Environment

Results of running `dbt --version`:

```sh
# Add the results here
```

Please paste the contents of your `packages.yml` file here:

```yml
packages:
  - name: dbt_utils
    package: dbt-labs/dbt_utils
    version: 1.3.0
  - name: dbt_date
    package: godatadriven/dbt_date
    version: 0.12.0
  - name: audit_helper
    package: dbt-labs/audit_helper
    version: 0.12.1
  - name: salesforce_formula_utils
    package: fivetran/salesforce_formula_utils
     version: 0.10.0
   - name: dbt_artifacts
     package: brooklyn-data/dbt_artifacts
     version: 2.9.2
   - name: fivetran_utils
     package: fivetran/fivetran_utils
     version: 0.4.10
  ...
```

**Comment by inactivekathework** [comment]
Is fixed in this PR 
fix: Removed an obsolete endmacro statement [#502](https://github.com/brooklyn-data/dbt_artifacts/pull/502)

**Comment by ulidtko** [comment]
Actually fixed in #498 — and released in package version `2.9.3` or newer.

```yaml
# packages.yml

packages:
  [...]

  - package: brooklyn-data/dbt_artifacts
    version: 2.10.0
```
